version: "3.9"
services:
  web:
    build: .
    image: myapp-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - sqlite:/app/prisma

volumes:
  sqlite:
